setConf TZ_REPORT_ACT 0
setConf RTL_FSDB ""
setConf EXPORT_PARASITIC 1
setConf LINK_LIBRARY ""
setConf DESIGN_NAME alu_64bit_ref
setConf TZ_COMPILE_CMDS ""
setConf RTL_SAIF ""
setConf TZ_SETUP_CMDS ""
setConf ELABORATED_BLOCK ""
setConf MCMM_FLOW 1
setConf NCORES 8
setConf FSDB_SYSVER 0
setConf ZZ_SETUP_CMDS ""
setConf MERGE_SAIF_OPT ""
setConf ZZ_SETUP ""
setConf REPORT 0
setConf RTL_VCD ""
setConf AZ_SETUP_CMDS ""
setConf PP_POSTCMD ""
setConf TECH_LIB ""
setConf SDC_SETUP ""
setConf SCENARIO func.ss0p95v125c
setConf RUN_ON_ELAB 0
setConf BACKUP_LIBRARY_NAMES ""
setConf EXPORT_CG_INFO 0
setConf MODULE_NAME ""
setConf REF_LIBS ""
setConf IMPORT_XREF 1
setConf ACTIVITY_FILE_PATH ""
setConf HIER_NDM_READ 0
setConf CORNER ""
setConf FUSION_LIB 0
setConf EXIT_AFTER ""
setConf FSDB_TIME ""
setConf EXPORT_CONSTRAINT 1
setConf PP_SHELL pwr_shell
setConf CREATE_LIB_OPT ""
setConf PP_PRE_PWR_CMDS ""
setConf INSTANCE_NAME ""
setConf PRE_SYNTH_EXIT 0
setConf STRIP_PATH ""
setConf EVENT_SHIFT 0
setConf PP_SETUP ""
setConf SKIP_GPD 0
setConf SEARCH_PATH ""
setConf TECH_FILE ""
setConf EXPORT_UPF 1
setConf RTL_LIST_FILE ""
setConf MODE ""
setConf TZ_SHELL tz_shell
setConf POWERLIB_ONLY 0
setConf EXTENDED_NAME /home/net/jo045021/sp26/rtl-opt-proj/yosys-internal/rtla-synthesis/synthesis_output/alu_64bit_ref/alu_64bit_ref.dlib:alu_64bit_ref.design
setConf EXPORT_MAPPING 1
setConf PP_DBFLOW 0
setConf TZ_SETUP ""
setConf CURRENT_SCENARIO func.ss0p95v125c
setConf USE_SPEF 0
setConf AZ_SETUP ""
setConf RTL_FILES ""
setConf RTL_LIST_FILE_TYPE ""
setConf PP_PRE_PWR_SETUP ""
setConf ESSENTIAL_NAMEMAP -1
setConf READ_ACT_CMD ""
setConf OUTPUT_DIR RTLA_WORKSPACE
